site_name: NewTars-Blog
site_url: https://newtars.top

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details

extra_css:
  - assets/css/extra.css
  - assets/css/toc.css
  - assets/css/sidebar.css
  - assets/css/read-metrics.css

extra_javascript:
  - assets/js/mathjax-config.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/js/read-metrics.js

nav:
  - Welcome: index.md
  - as_student:
    - as_student/index.md
    - 前言: as_student/preface.md
    - 计算机组成原理:
      - as_student/computer_organization/index.md
  - as_staff:
    - as_staff/index.md
  - as_reader:
    - as_reader/index.md
  - as_foreigner:
    - as_foreigner/index.md
  - casual_notes:
    - casual_notes/index.md
      -2026-09-22/2026-09-22.md
